apiVersion: v1
data:
  DISCORD_TOKEN: #{discord.token}#
kind: ConfigMap
metadata:
  namespace: prod
  name: xi-jingping-bot-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xi-jinping-bot
  name: xi-jinping-bot
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xi-jinping-bot
  template:
    metadata:
      labels:
        app: xi-jinping-bot
    spec:
      containers:
      - image: #{deployment.image}#
        name: xi-jinping-bot
        envFrom:
          - configMapRef:
              name: xi-jingping-bot-config
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
---





