kind: Deployment
apiVersion: apps/v1
metadata:
  name: xi-jinping-bot
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xi-jinping-bot
  template:
    metadata:
      labels:
        app: xi-jinping-bot
    spec:
      containers:
        - name: xi-jinping-bot
          image: #{deployment.image.name}#
          ports:
            - name: http-api
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
